### ISSUE TITLE
1.0.6版本提示下载失败

### ISSUE THREAD

**Issue by AquaSimulacra** [yaobiao131/downkyicore#20]

**Comment by yaobiao131** [comment]
可以提供一下日志和下载链接吗，是每一个链接都下载失败吗

**Comment by AquaSimulacra** [comment]
2024-01-22 22:39:49   [1]   ERROR   DownKyi.Core  文件大小不匹配
   at DownKyi.Core.Utils.Encryptor.Encryptor.DecryptFile(String inFile, String outFile, String password)
   at DownKyi.Core.BiliApi.Login.LoginHelper.GetLoginInfoCookies()
----------------------------------------------------------------------------------------------------------------------
2024-01-22 22:39:49   [10]   DEBUG   AriaServer  01/22 22:39:49 [[1;32mNOTICE[0m] IPv4 RPC: listening on TCP port 6800
----------------------------------------------------------------------------------------------------------------------
2024-01-22 22:39:50   [11]   ERROR   DownKyi.Core  文件大小不匹配
   at DownKyi.Core.Utils.Encryptor.Encryptor.DecryptFile(String inFile, String outFile, String password)
   at DownKyi.Core.BiliApi.Login.LoginHelper.GetLoginInfoCookies()
----------------------------------------------------------------------------------------------------------------------
2024-01-22 22:39:53   [1]   DEBUG   NavigateToView  NavigationView: PageLogin, Parameter: 
----------------------------------------------------------------------------------------------------------------------
2024-01-22 22:39:54   [11]   ERROR   DownKyi.Core  文件大小不匹配
   at DownKyi.Core.Utils.Encryptor.Encryptor.DecryptFile(String inFile, String outFile, String password)
   at DownKyi.Core.BiliApi.Login.LoginHelper.GetLoginInfoCookies()
----------------------------------------------------------------------------------------------------------------------
2024-01-22 22:39:55   [11]   DEBUG   PageLogin  https://passport.bilibili.com/h5-app/passport/login/scan?navhide=1&qrcode_key=ff9c982fe92e500801e5a21931ffc3e1&from=
----------------------------------------------------------------------------------------------------------------------
2024-01-22 22:39:57   [11]   ERROR   DownKyi.Core  文件大小不匹配
   at DownKyi.Core.Utils.Encryptor.Encryptor.DecryptFile(String inFile, String outFile, String password)
   at DownKyi.Core.BiliApi.Login.LoginHelper.GetLoginInfoCookies()
----------------------------------------------------------------------------------------------------------------------
2024-01-22 22:39:59   [11]   ERROR   DownKyi.Core  文件大小不匹配
   at DownKyi.Core.Utils.Encryptor.Encryptor.DecryptFile(String inFile, String outFile, String password)
   at DownKyi.Core.BiliApi.Login.LoginHelper.GetLoginInfoCookies()
----------------------------------------------------------------------------------------------------------------------
2024-01-22 22:40:01   [11]   ERROR   DownKyi.Core  文件大小不匹配
   at DownKyi.Core.Utils.Encryptor.Encryptor.DecryptFile(String inFile, String outFile, String password)
   at DownKyi.Core.BiliApi.Login.LoginHelper.GetLoginInfoCookies()
----------------------------------------------------------------------------------------------------------------------
2024-01-22 22:40:03   [11]   ERROR   DownKyi.Core  文件大小不匹配
   at DownKyi.Core.Utils.Encryptor.Encryptor.DecryptFile(String inFile, String outFile, String password)
   at DownKyi.Core.BiliApi.Login.LoginHelper.GetLoginInfoCookies()
----------------------------------------------------------------------------------------------------------------------
2024-01-22 22:40:05   [11]   ERROR   DownKyi.Core  文件大小不匹配
   at DownKyi.Core.Utils.Encryptor.Encryptor.DecryptFile(String inFile, String outFile, String password)
   at DownKyi.Core.BiliApi.Login.LoginHelper.GetLoginInfoCookies()
----------------------------------------------------------------------------------------------------------------------
2024-01-22 22:40:07   [11]   ERROR   DownKyi.Core  文件大小不匹配
   at DownKyi.Core.Utils.Encryptor.Encryptor.DecryptFile(String inFile, String outFile, String password)
   at DownKyi.Core.BiliApi.Login.LoginHelper.GetLoginInfoCookies()
----------------------------------------------------------------------------------------------------------------------
2024-01-22 22:40:10   [11]   ERROR   DownKyi.Core  文件大小不匹配
   at DownKyi.Core.Utils.Encryptor.Encryptor.DecryptFile(String inFile, String outFile, String password)
   at DownKyi.Core.BiliApi.Login.LoginHelper.GetLoginInfoCookies()
----------------------------------------------------------------------------------------------------------------------
2024-01-22 22:40:12   [11]   ERROR   DownKyi.Core  文件大小不匹配
   at DownKyi.Core.Utils.Encryptor.Encryptor.DecryptFile(String inFile, String outFile, String password)
   at DownKyi.Core.BiliApi.Login.LoginHelper.GetLoginInfoCookies()

**Comment by AquaSimulacra** [comment]
有可能是我的更新方法过于暴力。。。把downkyi和downkyicore的文件混到一起去了
