### ISSUE TITLE
1.0.8版频繁崩溃

### ISSUE THREAD

**Issue by Rangtian** [yaobiao131/downkyicore#69]
批量下载[凡人修仙传](https://www.bilibili.com/bangumi/play/ss28747)，短则一启动立马崩溃，长则下个4、5集就崩溃。事件查看器里报错信息如下：

> 错误应用程序名称: DownKyi.exe，版本: 1.0.8.0，时间戳: 0x65ab0000
错误模块名称: KERNELBASE.dll，版本: 10.0.22621.3374，时间戳: 0x3069ce37
异常代码: 0xe0434352
错误偏移量: 0x00000000000653ac
错误进程 ID: 0x0x2204
错误应用程序启动时间: 0x0x1DA824ABE982D0E
错误应用程序路径: C:\Studio\DownKyi\DownKyi.exe
错误模块路径: C:\Windows\System32\KERNELBASE.dll
报告 ID: d1782ba4-b4eb-4ca2-ab92-ee1913905269

> Application: DownKyi.exe
CoreCLR Version: 6.0.2724.6912
.NET Version: 6.0.27
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.WebException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 [::ffff:180.97.245.31]:4483 (xy180x97x245x31xy.mcdn.bilivideo.cn:4483)
 ---> System.Net.Http.HttpRequestException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 [::ffff:180.97.245.31]:4483 (xy180x97x245x31xy.mcdn.bilivideo.cn:4483)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 [::ffff:180.97.245.31]:4483
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
--- End of stack trace from previous location ---
   at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
   at System.Net.Sockets.Socket.Connect(String host, Int32 port)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.HttpWebRequest.<>c__DisplayClass216_0.<<CreateHttpClient>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellation(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.HttpWebRequest.SendRequest(Boolean async)
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at DownKyi.Core.Downloader.PartialDownloader.DownloadProcedure(Action`1 config)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by yaobiao131** [comment]
由于没有详细信息无法知道详细情况、只有下载这个视频还是所有的视频都会，这个是番剧，番剧的风控目前没有修复，可以尝试投稿会不会崩溃

**Comment by Rangtian** [comment]
> 由于没有详细信息无法知道详细情况、只有下载这个视频还是所有的视频都会，这个是番剧，番剧的风控目前没有修复，可以尝试投稿会不会崩溃

投稿应该是不会崩溃，我印象里没崩过。应用程序我已经换成1.59覆盖1.61了，原有的应用程序日志没保留。

**Comment by yaobiao131** [comment]
> > 由于没有详细信息无法知道详细情况、只有下载这个视频还是所有的视频都会，这个是番剧，番剧的风控目前没有修复，可以尝试投稿会不会崩溃
> 
> 投稿应该是不会崩溃，我印象里没崩过。应用程序我已经换成1.59覆盖1.61了，原有的应用程序日志没保留。

好的，番剧我后续在看看能不能修下
