### ISSUE TITLE
下载总是失败或是闪退

### ISSUE THREAD

**Issue by xzqaaa** [yaobiao131/downkyicore#78]
如果用aria2下载器会疯狂跳下载失败，如果用内建下载下载器会不停的闪退，几乎很难下载完一个视频

**Comment by shawgui** [comment]
我也是，用软件内部aria2下载会闪退

**Comment by yaobiao131** [comment]
麻烦提供一下下载的url

**Comment by shawgui** [comment]
我大概知道为什么了，点击下载会电脑cpu直接占满

**Comment by shawgui** [comment]
> 麻烦提供一下下载的url

开着chrome浏览器，不知道这个会不会有影响

**Comment by shawgui** [comment]
> 我这边测试没有问题
刚才关闭chrome浏览器后下载还是闪退，不过CPU占用率没有爆炸，但是还是不行

**Comment by shawgui** [comment]
> 可以看看windows事件管理器里面的闪退原因吗

错误应用程序名称: DownKyi.exe，版本: 1.0.9.0，时间戳: 0x65d50000
错误模块名称: KERNELBASE.dll，版本: 10.0.19041.4291，时间戳: 0xa956ff71
异常代码: 0xe0434352
错误偏移量: 0x000000000002ab89
错误进程 ID: 0x3590
错误应用程序启动时间: 0x01da957fff78b409
错误应用程序路径: E:\哔哩哔哩下载姬\DownKyi-1.0.9-1.win-x64\DownKyi.exe
错误模块路径: C:\WINDOWS\System32\KERNELBASE.dll
报告 ID: b0ab2a74-c012-4cac-8589-06f7b18ed8dd
错误程序包全名: 
错误程序包相对应用程序 ID:

**Comment by shawgui** [comment]
> 可以看看windows事件管理器里面的闪退原因吗

大大，两个同时出现的错误都发给您了

**Comment by shawgui** [comment]
> 可以看看windows事件管理器里面的闪退原因吗

  刚才为了怕中文路径有影响，改成英文，依旧不行

**Comment by yaobiao131** [comment]
尝试关闭重复文件自动添加后缀试下

**Comment by shawgui** [comment]
> 尝试关闭重复文件自动添加后缀试下

    关闭后可以了，谢谢大佬

**Comment by 2987947281** [comment]
@yaobiao131 
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.EntryPointNotFoundException: Unable to find an entry point named 'videoio_VideoCapture_new3' in shared library 'OpenCvSharpExtern'.
   at OpenCvSharp.Internal.NativeMethods.videoio_VideoCapture_new3(Int32 device, Int32 apiPreference, IntPtr& returnValue)
   at OpenCvSharp.VideoCapture..ctor(Int32 index, VideoCaptureAPIs apiPreference)
   at AvaloniaApplication5.MainWindow.ScanBtn_Click(Object sender, RoutedEventArgs e) in /home/ubuntu/桌面/AvaloniaApplication5/AvaloniaApplication5/MainWindow.axaml.cs:line 77
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Controls.Button.OnClick()
   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs e)
   at Avalonia.Input.InputElement.<>c.<.cctor>b__32_9(InputElement x, PointerReleasedEventArgs e)
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers, IInputElement hitTest)
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e)
   at Avalonia.Threading.Dispatcher.Send(SendOrPostCallback action, Object arg, Nullable`1 priority)
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e)
   at Avalonia.ManualRawEventGrouperDispatchQueue.DispatchNext()
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.StartCore(String[] args)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
   at AvaloniaApplication5.Program.Main(String[] args) in /home/ubuntu/桌面/AvaloniaApplication5/AvaloniaApplication5/Program.cs:line 13
大佬可不可以看看我这个是什么问题我用的opencvsharp和opencv都是4.1的包
