### ISSUE TITLE
内建下载器闪退问题

### ISSUE THREAD

**Issue by lhyhopex** [yaobiao131/downkyicore#96]
使用自带的aira2无法下载视频报download aborted和unreachable network，尝试修改端口或调整线程数无效。
改为使用内建下载器后可正常下载视频但不定期自动闪退，与同时下载的视频数量/下载列表的视频总数/线程数设置都无关，可能发生在音频下载，视频下载，混流的任何一个阶段（cpu内存网卡占用也都不超过10%应该也不是性能问题）日志中查找error字样，大致有如下四类结果：
2024/5/15 7:22:41   [44]   ERROR   BuiltinDownloadService.DownloadByBuiltin()  Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.Sum[TSource](IEnumerable`1 source, Func`2 selector)
   at DownKyi.Core.Downloader.MultiThreadDownloader.get_TotalSpeedInBytes()
   at DownKyi.Services.Download.BuiltinDownloadService.<>c__DisplayClass14_0.<DownloadByBuiltin>b__1(Object sender, EventArgs e)

2024/5/15 7:23:28   [25]   ERROR   DbHelper ExecuteNonQuery()  SQLite Error 19: 'UNIQUE constraint failed: downloaded.id'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at DownKyi.Core.Storage.Database.DbHelper.ExecuteNonQuery(String sql, Action`1 action)

2024/5/15 7:02:57   [19]   ERROR   StorageUtils  The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at DownKyi.Core.Storage.StorageUtils.DownloadImage(String url, String localFile)

2024/5/15 7:03:39   [1]   ERROR   PageDownloadManagerDownloadFinished.SetDialogService()  Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at System.Collections.Generic.List`1.CopyTo(T[] array, Int32 arrayIndex)
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at DownKyi.ViewModels.DownloadManager.ViewDownloadFinishedViewModel.<SetDialogService>b__18_0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at DownKyi.ViewModels.DownloadManager.ViewDownloadFinishedViewModel.SetDialogService()

**Comment by yaobiao131** [comment]
内建下载器不是很稳定。后续会持续优化，还是建议用aria2下载

**Comment by lhyhopex** [comment]
aria2我在使用时无法下载，日志会出现报错：
2024/5/16 11:53:38   [9]   DEBUG   AriaServer  Exception: [AbstractCommand.cc:312] errorCode=1 Network problem has occurred. cause:A socket operation was attempted to an unreachable network.
而导致下载失败，关闭软件重新打开后会主动弹窗报Aria2错误：
2024/5/16 11:54:42   [12]   DEBUG   AriaServer  05/16 11:54:42 [[1;31mERROR[0m] CUID#29 - Download aborted.
2024/5/16 11:54:42   [12]   DEBUG   AriaServer  Exception: [AbstractCommand.cc:312] errorCode=1 Network problem has occurred. cause:A socket operation was attempted to an unreachable network.
使用的就是默认设置下的自带aria2，尝试修改端口号无果

**Comment by lhyhopex** [comment]
检查防火墙规则也都在的，对任何端口tcp/udp都有

**Comment by Norman-Jean** [comment]
换老版aria2c.exe试试，原版的那个
